server:
  port: 8089

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: com.example.takeout_server.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

